let adminProdState={q:'',cat:'Todos',sub:'Todos'};
function setAdminProdSearch(v){adminProdState.q=v||'';rProd();}
function setAdminProdFilter(cat='Todos',sub='Todos'){adminProdState.cat=cat;adminProdState.sub=sub;rProd();}
function clearAdminProdFilter(){adminProdState={q:'',cat:'Todos',sub:'Todos'};rProd();}
function ensureFinanceFlags(){D.expenses.forEach(e=>{if(!e.status)e.status='activo';});}
function activeExpenses(){ensureFinanceFlags();return D.expenses.filter(e=>e.status!=='anulado');}
function moneyColorPalette(n){const base=['#66c7f4','#8b5cf6','#4fd1c5','#f59e0b','#22c55e','#ef4444','#ec4899','#38bdf8'];return Array.from({length:n},(_,i)=>base[i%base.length]);}
function miniBarChart(data,{colors=null,currency='',height=180,empty='Sin datos para graficar',detailType='none',panelId='',totalLabel=''}={}){
  const arr=(data||[]).filter(d=>Number(d.value)>0);
  const total=arr.reduce((s,d)=>s+Number(d.value||0),0);
  if(!arr.length) return `<div style="font-size:12px;color:#7b93ad;padding:18px 0">${empty}</div>`;
  const max=Math.max(...arr.map(d=>Math.abs(d.value)),1);
  const bw=54,gap=22,left=18,base=height-32;
  const width=Math.max(300,left+arr.length*(bw+gap)+10);
  const pal=colors&&colors.length?colors:moneyColorPalette(arr.length);
  const bars=arr.map((d,i)=>{const h=Math.max(14,(Math.abs(d.value)/max)*(height-68));const x=left+i*(bw+gap);const y=base-h;const fill=pal[i%pal.length];const key=String(d.key||d.label).replace(/'/g,"&#39;");const click=detailType!=='none'&&panelId?`onclick="showChartDetail('${detailType}','${key}','${panelId}')" style="cursor:pointer"`:'';return `<g ${click}><rect x="${x}" y="${y}" rx="12" ry="12" width="${bw}" height="${h}" fill="${fill}" opacity="0.9"></rect><text x="${x+bw/2}" y="${y-8}" text-anchor="middle" fill="#dff6ff" font-size="11" font-family="Inter">${currency}${Number(d.value).toFixed(Number.isInteger(d.value)?0:2)}</text><text x="${x+bw/2}" y="${height-10}" text-anchor="middle" fill="#7b93ad" font-size="10" font-family="Inter">${esc(d.label)}</text></g>`}).join('');
  return `<div style="overflow:auto"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><span style="font-size:11px;color:#7b93ad">${totalLabel||'Total'}</span><strong style="font-size:13px;color:#e6f8ff">${currency}${total.toFixed(2)}</strong></div><svg viewBox="0 0 ${width} ${height}" width="100%" height="${height}" role="img"><line x1="10" y1="${base}" x2="${width-10}" y2="${base}" stroke="#22304a" stroke-width="1"></line>${bars}</svg></div>`;
}
function monthShort(dateStr){const d=new Date(dateStr);return isNaN(d)?String(dateStr).slice(5,7):d.toLocaleDateString('es-VE',{month:'short'});}
function statusChartData(){const m={pendiente:0,completado:0,cancelado:0};D.orders.forEach(o=>{m[o.status]=(m[o.status]||0)+1;});return Object.entries(m).map(([key,value])=>({key,label:key,value}));}
function categoryChartData(){ensureTaxonomy();const m={};D.products.forEach(p=>{m[p.cat]=(m[p.cat]||0)+1;});return Object.entries(m).map(([key,value])=>({key,label:key.length>10?key.slice(0,10)+'…':key,value}));}
function productSalesChartData(){const m={};D.orders.filter(o=>o.status==='completado').forEach(o=>{(o.products||[]).forEach(p=>{m[p]=(m[p]||0)+1;});});return Object.entries(m).map(([key,value])=>({key,label:key.length>12?key.slice(0,12)+'…':key,value}));}
function monthlySalesData(){const m={};D.orders.filter(o=>o.status==='completado').forEach(o=>{const key=o.date?.slice(0,7)||'Sin fecha';m[key]=(m[key]||0)+o.total;});return Object.entries(m).sort().map(([key,value])=>({key,label:monthShort(key+'-01'),value}));}
function paymentChartData(){const m={};D.orders.filter(o=>o.status==='completado').forEach(o=>{m[o.payment]=(m[o.payment]||0)+o.total;});return Object.entries(m).map(([key,value])=>({key,label:key.length>10?key.slice(0,10)+'…':key,value}));}
function expenseTypeChartData(){const m={};activeExpenses().forEach(e=>{m[e.type]=(m[e.type]||0)+e.amount;});return Object.entries(m).map(([key,value])=>({key,label:key.length>10?key.slice(0,10)+'…':key,value}));}
function getCategoryStockSummary(){ensureTaxonomy();const out=[];Object.entries(D.taxonomy).forEach(([cat,subs])=>{const catProds=D.products.filter(p=>p.cat===cat);out.push({cat,sub:'Todos',stock:catProds.reduce((s,p)=>s+(p.stock||0),0)});(subs||[]).forEach(sub=>{const list=catProds.filter(p=>(p.subcat||'General')===sub);out.push({cat,sub,stock:list.reduce((s,p)=>s+(p.stock||0),0)});});});return out;}
function showChartDetail(type,key,panelId='chart-detail'){const panel=g(panelId);if(!panel)return;ensureTaxonomy();ensureFinanceFlags();let html='';
if(type==='category'){const items=D.products.filter(p=>p.cat===key);html=`<h3 style="font-size:14px;color:#66c7f4;margin-bottom:10px">${esc(key)}</h3>${items.map(p=>`<button onclick="goToProductEdit(${p.id})" style="width:100%;text-align:left;background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px;color:#e2e8f0;cursor:pointer"><div style="font-weight:700">${esc(p.name)}</div><div style="font-size:11px;color:#7b93ad">${esc(p.subcat||'General')} · Stock ${p.stock}</div></button>`).join('')||'<p style="color:#7b93ad">Sin productos</p>'}`;}
else if(type==='orderStatus'){const items=D.orders.filter(o=>o.status===key);html=`<h3 style="font-size:14px;color:#8b5cf6;margin-bottom:10px">Pedidos ${esc(key)}</h3>${items.map(o=>`<div style="background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px"><div style="font-weight:700;color:#e2e8f0">${esc(o.client)}</div><div style="font-size:11px;color:#7b93ad">${esc((o.products||[]).join(', '))} · $${o.total}</div></div>`).join('')||'<p style="color:#7b93ad">Sin pedidos</p>'}`;}
else if(type==='payment'){const items=D.orders.filter(o=>o.status==='completado'&&o.payment===key);html=`<h3 style="font-size:14px;color:#8b5cf6;margin-bottom:10px">Ventas por ${esc(key)}</h3>${items.map(o=>`<div style="background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px"><div style="font-weight:700;color:#e2e8f0">${esc(o.client)}</div><div style="font-size:11px;color:#7b93ad">${esc((o.products||[]).join(', '))} · $${o.total}</div></div>`).join('')||'<p style="color:#7b93ad">Sin ventas</p>'}`;}
else if(type==='monthSales'){const items=D.orders.filter(o=>o.status==='completado'&&(o.date||'').slice(0,7)===key);html=`<h3 style="font-size:14px;color:#66c7f4;margin-bottom:10px">Ventas ${esc(monthShort(key+'-01'))}</h3>${items.map(o=>`<div style="background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px"><div style="font-weight:700;color:#e2e8f0">${esc(o.client)}</div><div style="font-size:11px;color:#7b93ad">${esc((o.products||[]).join(', '))} · $${o.total}</div></div>`).join('')||'<p style="color:#7b93ad">Sin ventas</p>'}`;}
else if(type==='expenseType'){const items=activeExpenses().filter(e=>e.type===key);html=`<h3 style="font-size:14px;color:#ef4444;margin-bottom:10px">Gastos ${esc(key)}</h3>${items.map(e=>`<button onclick="goToExpense(${e.id})" style="width:100%;text-align:left;background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px;color:#e2e8f0;cursor:pointer"><div style="font-weight:700">${esc(e.desc)}</div><div style="font-size:11px;color:#7b93ad">${e.date} · ${e.amount} ${e.currency}</div></button>`).join('')||'<p style="color:#7b93ad">Sin gastos activos</p>'}`;}
else if(type==='productSales'){const items=D.products.filter(p=>p.name===key);html=`<h3 style="font-size:14px;color:#4fd1c5;margin-bottom:10px">Producto ${esc(key)}</h3>${items.map(p=>`<button onclick="goToProductEdit(${p.id})" style="width:100%;text-align:left;background:#0d0d20;border:1px solid #1e1e40;border-radius:10px;padding:10px;margin-bottom:8px;color:#e2e8f0;cursor:pointer"><div style="font-weight:700">${esc(p.name)}</div><div style="font-size:11px;color:#7b93ad">${esc(p.cat)} · ${esc(p.subcat||'General')} · Stock ${p.stock}</div></button>`).join('')||'<p style="color:#7b93ad">No se encontró el producto</p>'}`;}
panel.innerHTML=html||'<p style="color:#7b93ad">Selecciona una barra para ver el detalle.</p>';}
function goToProductEdit(id){const btn=[...document.querySelectorAll('.nb')].find(b=>b.textContent.includes('Productos'));if(btn){sT('p',btn);setTimeout(()=>eprod(id),80);}}
function goToExpense(id){const btn=[...document.querySelectorAll('.nb')].find(b=>b.textContent.includes('Gastos'));if(btn){sT('e',btn);setTimeout(()=>{const row=g('exp-'+id);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.style.boxShadow='0 0 0 2px #ef4444';setTimeout(()=>row.style.boxShadow='',1600);}},120);}}
