function rFin(){
  ensureFinanceFlags();
  const done=D.orders.filter(o=>o.status==='completado');const sales=done.reduce((s,o)=>s+o.total,0);const exps=activeExpenses().reduce((s,e)=>s+(e.currency==='USD'?e.amount:(e.amount/(D.cfg.tasaBCV||1))),0);const profit=sales-exps;const mg=sales>0?((profit/sales)*100).toFixed(1):0;const cfg=D.cfg;const pmt=done.reduce((a,o)=>{a[o.payment]=(a[o.payment]||0)+o.total;return a},{});
  g('tab-f').innerHTML=`<div style="margin-bottom:22px"><h2 style="font-size:20px;background:linear-gradient(135deg,#66c7f4,#7c5cff);-webkit-background-clip:text;-webkit-text-fill-color:transparent">Finanzas</h2></div>
  <div class="g4" style="margin-bottom:20px">${[{i:'📈',l:'Ingresos',v:'$'+sales.toFixed(2),c:'#22c55e'},{i:'📉',l:'Gastos',v:'$'+exps.toFixed(2),c:'#ef4444'},{i:'💰',l:'Ganancia',v:'$'+profit.toFixed(2),c:profit>=0?'#66c7f4':'#ef4444'},{i:'📊',l:'Margen',v:mg+'%',c:'#a855f7'}].map(c=>`<div class="sc" style="border:1px solid ${c.c}22;border-left:3px solid ${c.c}"><div>${c.i}</div><div style="font-size:18px;font-weight:700;color:${c.c};font-family:'Oxanium',sans-serif;margin-top:5px">${c.v}</div><div style="font-size:11px;color:#7b93ad">${c.l}</div></div>`).join('')}</div>
  <div class="panel" style="padding:18px;margin-bottom:16px"><h3 style="font-size:13px;margin-bottom:12px;color:#f59e0b">💱 Multi-moneda</h3><div class="g3">${[['USD 💵','#66c7f4','$'+profit.toFixed(2)],[`Bs ×${cfg.tasaBCV}`,'#f59e0b','Bs.'+(profit*cfg.tasaBCV).toFixed(2)],[`CLP ×${cfg.tasaCLP}`,'#a855f7','$'+(profit*cfg.tasaCLP).toLocaleString()]].map(([l,c,v])=>`<div style="text-align:center;padding:14px;background:#060610;border-radius:9px"><div style="font-size:16px;font-weight:700;color:${c}">${v}</div><div style="font-size:10px;color:#7b93ad;margin-top:3px">${l}</div></div>`).join('')}</div></div>
  <div style="display:grid;grid-template-columns:1fr 1fr 340px;gap:18px;margin-bottom:16px;align-items:start">
    <div class="panel" style="padding:18px"><h3 style="font-size:13px;margin-bottom:12px;color:#66c7f4">Ventas por mes</h3>${miniBarChart(monthlySalesData(),{colors:moneyColorPalette(monthlySalesData().length),currency:'$',detailType:'monthSales',panelId:'fin-detail',totalLabel:'Total ventas'})}</div>
    <div class="panel" style="padding:18px"><h3 style="font-size:13px;margin-bottom:12px;color:#a855f7">Ingresos por método</h3>${miniBarChart(paymentChartData(),{colors:moneyColorPalette(paymentChartData().length),currency:'$',detailType:'payment',panelId:'fin-detail',totalLabel:'Ingresos por método'})}</div>
    <div class="panel" style="padding:18px;min-height:280px" id="fin-detail"><p style="color:#7b93ad;font-size:12px">Toca una barra para ver el detalle financiero.</p></div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr 340px;gap:18px;align-items:start">
    <div class="panel" style="padding:18px"><h3 style="font-size:13px;margin-bottom:12px;color:#ef4444">Gastos por tipo</h3>${miniBarChart(expenseTypeChartData(),{colors:moneyColorPalette(expenseTypeChartData().length),currency:'$',detailType:'expenseType',panelId:'fin-detail-2',totalLabel:'Gastos activos'})}</div>
    <div class="panel" style="padding:18px"><h3 style="font-size:13px;margin-bottom:12px;color:#4fd1c5">Por Método</h3>${Object.entries(pmt).map(([m,t])=>`<div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #0f0f25"><span>${m}</span><span style="color:#66c7f4;font-weight:700">$${t.toFixed(2)}</span></div>`).join('')||'<p style="color:#7b93ad;font-size:12px">Sin ventas completadas</p>'}</div>
    <div class="panel" style="padding:18px;min-height:280px" id="fin-detail-2"><p style="color:#7b93ad;font-size:12px">Aquí aparecerán gastos, ventas y movimientos relacionados.</p></div>
  </div>`;
}

function rCalc(){
  const cfg=D.cfg;
  g('tab-k').innerHTML=`<div style="margin-bottom:22px"><h2 style="font-size:20px;background:linear-gradient(135deg,#00e5ff,#0066aa);-webkit-background-clip:text;-webkit-text-fill-color:transparent">Calculadoras</h2></div>
  <div class="g2">
    <div class="panel" style="padding:22px;border:1px solid #00e5ff22"><h3 style="font-size:14px;margin-bottom:16px;color:#00e5ff">🧮 Precio con Margen</h3><label class="lbl">Costo (USD)</label><input id="cc" type="number" oninput="cMg()"/><div style="margin-top:14px"><label class="lbl" id="cmgl">Margen: 40%</label><input type="range" min="5" max="300" value="40" oninput="g('cmgl').textContent='Margen: '+this.value+'%';cMg()" id="cmgr" style="margin-top:8px;accent-color:#00e5ff;background:transparent;border:none;width:100%"/></div><div id="cmgres" style="display:none;margin-top:14px;background:#060610;border-radius:9px;padding:14px"></div></div>
    <div class="panel" style="padding:22px;border:1px solid #a855f722"><h3 style="font-size:14px;margin-bottom:16px;color:#a855f7">💱 Convertidor</h3><div style="display:flex;gap:10px;margin-bottom:12px"><div style="flex:1"><label class="lbl">Monto</label><input id="cca" type="number" oninput="cCv()"/></div><div style="flex:0 0 90px"><label class="lbl">Desde</label><select id="ccf" onchange="cCv()" style="margin-top:5px"><option value="USD">USD</option><option value="Bs">Bs</option><option value="CLP">CLP</option></select></div></div><div id="ccres"></div><div style="margin-top:10px;padding:9px;background:#060610;border-radius:8px;font-size:11px;color:#475569">BCV: Bs.${cfg.tasaBCV} · CLP: ${cfg.tasaCLP}</div></div>
    <div class="panel" style="padding:22px;border:1px solid #22c55e22"><h3 style="font-size:14px;margin-bottom:16px;color:#22c55e">🚚 Delivery</h3><label class="lbl">Zona</label><select id="czn" onchange="cDl()" style="margin-bottom:12px">${cfg.zones.map((z,i)=>`<option value="${i}">${z.name} · $${z.price}</option>`).join('')}</select><label class="lbl">Peso (kg)</label><input id="cwt" type="number" oninput="cDl()"/><div style="margin-top:14px;background:#060610;border-radius:9px;padding:14px"><div style="display:flex;justify-content:space-between"><span style="font-weight:700">Total:</span><div><div style="color:#22c55e;font-weight:700;font-family:'Oxanium',sans-serif;font-size:17px" id="cdlt">$2.00</div><div style="font-size:11px;color:#f59e0b" id="cdlb">Bs. ${(2*cfg.tasaBCV).toFixed(2)}</div></div></div></div></div>
    <div class="panel" style="padding:22px;border:1px solid #f59e0b22"><h3 style="font-size:14px;margin-bottom:16px;color:#f59e0b">🔒 Apartado</h3><label class="lbl">Precio (USD)</label><input id="cap" type="number" oninput="cAp()"/><div style="margin-top:14px"><label class="lbl" id="capl">Inicial: 50%</label><input type="range" min="10" max="90" step="10" value="50" oninput="g('capl').textContent='Inicial: '+this.value+'%';cAp()" id="capr" style="margin-top:8px;accent-color:#f59e0b;background:transparent;border:none;width:100%"/></div><div id="cares" style="display:none;margin-top:12px;background:#060610;border-radius:9px;padding:14px"></div></div>
  </div>`;
}
function cMg(){const c=parseFloat(g('cc').value)||0,mg=parseInt(g('cmgr').value)||40,cfg=D.cfg;if(!c){g('cmgres').style.display='none';return;}const s=(c*(1+mg/100)).toFixed(2);g('cmgres').style.display='block';g('cmgres').innerHTML=`<div style="font-size:26px;font-weight:700;color:#00e5ff;font-family:'Oxanium',sans-serif">$${s}</div><div style="font-size:12px;color:#f59e0b;margin-top:5px">Bs. ${(s*cfg.tasaBCV).toFixed(2)}</div><div style="border-top:1px solid #1e1e40;margin-top:8px;padding-top:8px;font-size:12px;color:#22c55e;font-weight:700">Ganancia: $${(s-c).toFixed(2)}</div>`;}
function cCv(){const a=parseFloat(g('cca').value)||0,f=g('ccf').value,cfg=D.cfg;if(!a){g('ccres').innerHTML='';return;}let r={};if(f==='USD')r={USD:a,Bs:(a*cfg.tasaBCV).toFixed(2),CLP:(a*cfg.tasaCLP).toLocaleString()};else if(f==='Bs')r={Bs:a,USD:(a/cfg.tasaBCV).toFixed(2),CLP:((a/cfg.tasaBCV)*cfg.tasaCLP).toLocaleString()};else r={CLP:a,USD:(a/cfg.tasaCLP).toFixed(2),Bs:((a/cfg.tasaCLP)*cfg.tasaBCV).toFixed(2)};g('ccres').innerHTML=`<div style="background:#060610;border-radius:9px;padding:14px">${Object.entries(r).map(([cur,val])=>`<div style="display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #0f0f25"><span style="font-size:13px;color:#475569">${cur}</span><strong style="color:${cur==='USD'?'#00e5ff':cur==='Bs'?'#f59e0b':'#a855f7'};font-size:15px">${val}</strong></div>`).join('')}</div>`;}
function cDl(){const z=parseInt(g('czn').value)||0,w=parseFloat(g('cwt').value)||0,base=D.cfg.zones[z]?.price||0,t=base+(w*0.5),cfg=D.cfg;g('cdlt').textContent='$'+t.toFixed(2);g('cdlb').textContent='Bs. '+(t*cfg.tasaBCV).toFixed(2);}
function cAp(){const p=parseFloat(g('cap').value)||0,pct=parseInt(g('capr').value)||50;if(!p){g('cares').style.display='none';return;}const d=(p*pct/100).toFixed(2),b=(p-d).toFixed(2);g('cares').style.display='block';g('cares').innerHTML=`<div style="display:flex;justify-content:space-between;margin-bottom:7px"><span style="font-size:12px;color:#475569">Inicial (${pct}%):</span><strong style="color:#22c55e">$${d}</strong></div><div style="display:flex;justify-content:space-between"><span style="font-size:12px;color:#475569">Saldo:</span><strong style="color:#f59e0b">$${b}</strong></div>`;}

